language: node_js

node_js:
  - 0.8

install:
  - npm install
  - npm install --quiet -g grunt-cli
  - npm install --quiet -g bower
  - bower install
before_script:
  - sleep 1
script: 
    - grunt test
notifications:
  irc:
    channels: "chat.freenode.net#bs-staff"
    skip_join: true
    on_success: change
    on_failure: change
